### PR TITLE
Add playlists API service endpoint

### PR DESCRIPTION
**Pull request by dennis531**
The added Playlist API Endpoint is based on the [opencast pull request with the playlists](https://github.com/opencast/opencast/pull/5478).

### CODE REVIEW

**Comment by ferishili** [comment]
Hi @dennis531,
thank you very much for your contribution, would you mind adding the whole documentation to the GitHub wiki as well?
Please take a look at the /api/** endpoints here: https://github.com/elan-ev/opencast-php-library/wiki/API-Endpoints

**Comment by ferishili** [comment]
The Using tests are failing, I would assume that is because of the version increment to `1.11.0` which is not yet provided by `stable.opencast.org`, therefore we need to make sure that version is only changed to 1.11.0 inside the `OcPlaylistsApiTest`!

**Comment by dennis531** [comment]
After the OC pull request is merged, I will add the wiki entry and implement the version handling in the tests. Perhaps the API could still change.

**Comment by dennis531** [comment]
The playlists api is documented at https://github.com/elan-ev/opencast-php-library/wiki/OcPlaylistsApi.

**Comment by dennis531** [comment]
@ferishili you have to add the library version in https://github.com/elan-ev/opencast-php-library/wiki/OcPlaylistsApi#version when you create a new library version.

**Comment by ferishili** [comment]
Hi @dennis531
Thank you very much for your contribution.

**Pull request merged**
